import { ReportDetail, DamageCategory, ReportStatus, PublicStatus } from "@/features/reports/types";
import { PUBLIC_STATUS_MAPPING } from "@/features/reports/status-machine";

export const SEED_REPORTS: ReportDetail[] = [
  {
    id: "rep-001",
    publicId: "RD-2026-0812",
    ownerId: "demo-user-reporter",
    title: "Deep Asphalt Pothole on Sukhumvit Soi 21",
    category: "pothole",
    publicStatus: "repairing",
    detailedStatus: "repairing",
    publicLatitude: 13.7392,
    publicLongitude: 100.5621,
    localityLabel: "Asok Montri Road, Watthana",
    description: "Large 15cm pothole in the left motorcycle lane creating a hazard during rush hour.",
    locationContext: "Near Asok BTS Station Exit 3",
    exactLocation: {
      latitude: 13.739182,
      longitude: 100.562085,
      accuracyMeters: 4.2,
      source: "gps",
      capturedAt: "2026-09-24T08:30:00Z",
      localityLabel: "Asok Montri Road, Watthana",
    },
    publicLocation: {
      latitude: 13.7392,
      longitude: 100.5621,
      localityLabel: "Asok Montri Road, Watthana",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-001",
        url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "sukhumvit_pothole.jpg",
        byteSize: 1240000,
        isSanitized: true,
        createdAt: "2026-09-24T08:30:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "pothole",
          score: 0.96,
          boundingBox: { x: 320, y: 240, width: 180, height: 120 },
        },
      ],
      primaryCategory: "pothole",
      suggestedSeverity: "high",
      summary: "Severe edge deformation and roadbed void detected. Recommended for urgent asphalt patch.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.96,
      isDemo: true,
    },
    operationalPriority: "p1",
    events: [
      {
        id: "evt-001",
        reportId: "rep-001",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Incident report submitted with photo evidence and GPS coordinates.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-24T08:30:00Z",
      },
      {
        id: "evt-002",
        reportId: "rep-001",
        fromStatus: "reported",
        toStatus: "acknowledged",
        publicNote: "Report acknowledged by Central District Operations Center.",
        actorName: "Operations Dispatch",
        actorRole: "staff",
        createdAt: "2026-09-24T09:15:00Z",
      },
      {
        id: "evt-003",
        reportId: "rep-001",
        fromStatus: "acknowledged",
        toStatus: "assessing",
        publicNote: "Field inspection crew dispatched for depth measurement.",
        actorName: "District Engineer P. Somchai",
        actorRole: "staff",
        createdAt: "2026-09-24T13:00:00Z",
      },
      {
        id: "evt-004",
        reportId: "rep-001",
        fromStatus: "assessing",
        toStatus: "scheduled",
        publicNote: "Milling and cold-mix resurfacing scheduled.",
        actorName: "Maintenance Planning",
        actorRole: "staff",
        scheduledFor: "2026-09-27T22:00:00Z",
        createdAt: "2026-09-25T10:00:00Z",
      },
      {
        id: "evt-005",
        reportId: "rep-001",
        fromStatus: "scheduled",
        toStatus: "repairing",
        publicNote: "Night crew is on-site with road milling equipment.",
        actorName: "Crew Alpha #3",
        actorRole: "staff",
        createdAt: "2026-09-27T22:30:00Z",
      },
    ],
    assignedTeam: {
      id: "team-01",
      name: "District Maintenance Unit 1",
      publicDisplayName: "Watthana Highway Maintenance Team",
    },
    version: 5,
    createdAt: "2026-09-24T08:30:00Z",
    updatedAt: "2026-09-27T22:30:00Z",
  },
  {
    id: "rep-002",
    publicId: "RD-2026-0819",
    ownerId: "demo-user-reporter",
    title: "Alligator Cracking on Rama IV Road",
    category: "crack",
    publicStatus: "reported",
    detailedStatus: "assessing",
    publicLatitude: 13.7258,
    publicLongitude: 100.5432,
    localityLabel: "Rama IV Road, Pathum Wan",
    description: "Extensive web-like surface cracking across middle lane near Lumphini intersection.",
    locationContext: "Opposite Lumphini Park Gate 2",
    exactLocation: {
      latitude: 13.725841,
      longitude: 100.543194,
      accuracyMeters: 5.8,
      source: "gps",
      capturedAt: "2026-09-25T11:20:00Z",
      localityLabel: "Rama IV Road, Pathum Wan",
    },
    publicLocation: {
      latitude: 13.7258,
      longitude: 100.5432,
      localityLabel: "Rama IV Road, Pathum Wan",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-002",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "rama4_cracks.jpg",
        byteSize: 980000,
        isSanitized: true,
        createdAt: "2026-09-25T11:20:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "crack",
          score: 0.91,
          boundingBox: { x: 200, y: 150, width: 400, height: 300 },
        },
      ],
      primaryCategory: "crack",
      suggestedSeverity: "medium",
      summary: "Fatigue cracking pattern observed. Surface seal recommended before monsoon rains.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.91,
      isDemo: true,
    },
    operationalPriority: "p2",
    events: [
      {
        id: "evt-010",
        reportId: "rep-002",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Report submitted via mobile camera.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-25T11:20:00Z",
      },
      {
        id: "evt-011",
        reportId: "rep-002",
        fromStatus: "reported",
        toStatus: "acknowledged",
        publicNote: "Logged into district infrastructure queue.",
        actorName: "Staff Dispatch",
        actorRole: "staff",
        createdAt: "2026-09-25T14:10:00Z",
      },
      {
        id: "evt-012",
        reportId: "rep-002",
        fromStatus: "acknowledged",
        toStatus: "assessing",
        publicNote: "Technical survey team reviewing road sub-base stability.",
        actorName: "Engineer N. Kittisak",
        actorRole: "staff",
        createdAt: "2026-09-26T09:00:00Z",
      },
    ],
    version: 3,
    createdAt: "2026-09-25T11:20:00Z",
    updatedAt: "2026-09-26T09:00:00Z",
  },
  {
    id: "rep-003",
    publicId: "RD-2026-0798",
    title: "Subsidence Depression on Phahonyothin Road",
    category: "subsidence",
    publicStatus: "fixed",
    detailedStatus: "resolved",
    publicLatitude: 13.7842,
    publicLongitude: 100.5489,
    localityLabel: "Phahonyothin, Phaya Thai",
    description: "Sunken manhole surround causing vehicle jolts.",
    locationContext: "Near Ari BTS Station Entrance",
    exactLocation: {
      latitude: 13.78419,
      longitude: 100.54889,
      accuracyMeters: 3.5,
      source: "gps",
      capturedAt: "2026-09-18T10:00:00Z",
      localityLabel: "Phahonyothin, Phaya Thai",
    },
    publicLocation: {
      latitude: 13.7842,
      longitude: 100.5489,
      localityLabel: "Phahonyothin, Phaya Thai",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-003",
        url: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "ari_subsidence.jpg",
        byteSize: 1120000,
        isSanitized: true,
        createdAt: "2026-09-18T10:00:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "subsidence",
          score: 0.88,
          boundingBox: { x: 150, y: 180, width: 320, height: 210 },
        },
      ],
      primaryCategory: "subsidence",
      suggestedSeverity: "high",
      summary: "Manhole surround elevation drop detected.",
      needsHumanReview: true,
      imageQualityIssues: [],
      confidenceScore: 0.88,
      isDemo: true,
    },
    operationalPriority: "p1",
    events: [
      {
        id: "evt-020",
        reportId: "rep-003",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Citizen report logged.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-18T10:00:00Z",
      },
      {
        id: "evt-021",
        reportId: "rep-003",
        fromStatus: "reported",
        toStatus: "acknowledged",
        publicNote: "Urgent inspection assigned.",
        actorName: "Operations Dispatch",
        actorRole: "staff",
        createdAt: "2026-09-18T11:00:00Z",
      },
      {
        id: "evt-022",
        reportId: "rep-003",
        fromStatus: "acknowledged",
        toStatus: "repairing",
        publicNote: "Concrete collar reinforced and asphalt level restored.",
        actorName: "Public Works Division",
        actorRole: "staff",
        createdAt: "2026-09-20T04:00:00Z",
      },
      {
        id: "evt-023",
        reportId: "rep-003",
        fromStatus: "repairing",
        toStatus: "resolved",
        publicNote: "Repairs inspected, asphalt cure completed, road fully reopened.",
        actorName: "Senior Inspector V. Prasert",
        actorRole: "staff",
        resolutionEvidenceUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=600&q=80",
        createdAt: "2026-09-21T07:00:00Z",
      },
    ],
    assignedTeam: {
      id: "team-02",
      name: "Phaya Thai Rapid Response",
      publicDisplayName: "Rapid Response Repair Unit",
    },
    resolvedAt: "2026-09-21T07:00:00Z",
    version: 4,
    createdAt: "2026-09-18T10:00:00Z",
    updatedAt: "2026-09-21T07:00:00Z",
  },
  {
    id: "rep-004",
    publicId: "RD-2026-0830",
    title: "Standing Water & Blocked Culvert on Sathorn Tai",
    category: "standing_water",
    publicStatus: "reported",
    detailedStatus: "scheduled",
    publicLatitude: 13.7214,
    publicLongitude: 100.5298,
    localityLabel: "South Sathorn Road, Sathon",
    description: "Curb gutter overflow causing 10cm standing puddle across bus stop lane.",
    locationContext: "Near Chong Nonsi BRT Bridge",
    exactLocation: {
      latitude: 13.72138,
      longitude: 100.52982,
      accuracyMeters: 4.0,
      source: "gps",
      capturedAt: "2026-09-26T16:45:00Z",
      localityLabel: "South Sathorn Road, Sathon",
    },
    publicLocation: {
      latitude: 13.7214,
      longitude: 100.5298,
      localityLabel: "South Sathorn Road, Sathon",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-004",
        url: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "sathorn_water.jpg",
        byteSize: 1050000,
        isSanitized: true,
        createdAt: "2026-09-26T16:45:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "standing_water",
          score: 0.94,
          boundingBox: { x: 100, y: 220, width: 500, height: 260 },
        },
      ],
      primaryCategory: "standing_water",
      suggestedSeverity: "medium",
      summary: "Ponding water obscuring road markings and curb edge.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.94,
      isDemo: true,
    },
    operationalPriority: "p2",
    events: [
      {
        id: "evt-030",
        reportId: "rep-004",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Citizen submitted puddle report after heavy rain.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-26T16:45:00Z",
      },
      {
        id: "evt-031",
        reportId: "rep-004",
        fromStatus: "reported",
        toStatus: "acknowledged",
        publicNote: "Acknowledged by Drainage & Sewerage Operations.",
        actorName: "Staff Dispatch",
        actorRole: "staff",
        createdAt: "2026-09-26T17:30:00Z",
      },
      {
        id: "evt-032",
        reportId: "rep-004",
        fromStatus: "acknowledged",
        toStatus: "scheduled",
        publicNote: "High-pressure suction truck scheduled for drain clearing.",
        actorName: "Drainage Logistics",
        actorRole: "staff",
        scheduledFor: "2026-09-29T02:00:00Z",
        createdAt: "2026-09-27T08:00:00Z",
      },
    ],
    version: 3,
    createdAt: "2026-09-26T16:45:00Z",
    updatedAt: "2026-09-27T08:00:00Z",
  },
  {
    id: "rep-005",
    publicId: "RD-2026-0835",
    title: "Loose Concrete Debris on Rama IX Expressway Ramp",
    category: "obstruction",
    publicStatus: "reported",
    detailedStatus: "reported",
    publicLatitude: 13.7548,
    publicLongitude: 100.5784,
    localityLabel: "Rama IX Road, Huai Khwang",
    description: "Shattered concrete chunks scattered across the on-ramp lane.",
    locationContext: "On-ramp toward Chalong Rat Expressway",
    exactLocation: {
      latitude: 13.75478,
      longitude: 100.57842,
      accuracyMeters: 6.2,
      source: "manual",
      capturedAt: "2026-09-28T09:10:00Z",
      localityLabel: "Rama IX Road, Huai Khwang",
    },
    publicLocation: {
      latitude: 13.7548,
      longitude: 100.5784,
      localityLabel: "Rama IX Road, Huai Khwang",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-005",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "rama9_debris.jpg",
        byteSize: 890000,
        isSanitized: true,
        createdAt: "2026-09-28T09:10:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "obstruction",
          score: 0.97,
          boundingBox: { x: 250, y: 310, width: 220, height: 140 },
        },
      ],
      primaryCategory: "obstruction",
      suggestedSeverity: "high",
      summary: "Large debris fragments posing tire blowout and collision risks.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.97,
      isDemo: true,
    },
    operationalPriority: "p1",
    events: [
      {
        id: "evt-040",
        reportId: "rep-005",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "New report received. Awaiting dispatch review.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-28T09:10:00Z",
      },
    ],
    version: 1,
    createdAt: "2026-09-28T09:10:00Z",
    updatedAt: "2026-09-28T09:10:00Z",
  },
  {
    id: "rep-006",
    publicId: "RD-2026-0822",
    title: "Surface Rutting and Worn Asphalt on Silom Road",
    category: "surface_wear",
    publicStatus: "repairing",
    detailedStatus: "repairing",
    publicLatitude: 13.7275,
    publicLongitude: 100.5284,
    localityLabel: "Silom Road, Bang Rak",
    description: "Deep wheel-path ruts along the heavy bus corridor causing hydroplaning hazard.",
    locationContext: "Between Sala Daeng and Chong Nonsi",
    exactLocation: {
      latitude: 13.72752,
      longitude: 100.52839,
      accuracyMeters: 4.8,
      source: "gps",
      capturedAt: "2026-09-22T14:00:00Z",
      localityLabel: "Silom Road, Bang Rak",
    },
    publicLocation: {
      latitude: 13.7275,
      longitude: 100.5284,
      localityLabel: "Silom Road, Bang Rak",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-006",
        url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "silom_wear.jpg",
        byteSize: 1340000,
        isSanitized: true,
        createdAt: "2026-09-22T14:00:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "surface_wear",
          score: 0.89,
          boundingBox: { x: 80, y: 190, width: 440, height: 260 },
        },
      ],
      primaryCategory: "surface_wear",
      suggestedSeverity: "medium",
      summary: "Significant asphalt deformation along high-load vehicle trajectory.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.89,
      isDemo: true,
    },
    operationalPriority: "p3",
    events: [
      {
        id: "evt-050",
        reportId: "rep-006",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Initial submission received.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-22T14:00:00Z",
      },
      {
        id: "evt-051",
        reportId: "rep-006",
        fromStatus: "reported",
        toStatus: "repairing",
        publicNote: "Thermal micro-surfacing and resurfacing team active.",
        actorName: "Bang Rak Public Works",
        actorRole: "staff",
        createdAt: "2026-09-27T23:00:00Z",
      },
    ],
    assignedTeam: {
      id: "team-03",
      name: "Bang Rak Resurfacing Unit",
      publicDisplayName: "Central Urban Resurfacing Unit",
    },
    version: 2,
    createdAt: "2026-09-22T14:00:00Z",
    updatedAt: "2026-09-27T23:00:00Z",
  },
  {
    id: "rep-007",
    publicId: "RD-2026-0775",
    title: "Bridge Expansion Joint Gap on Krung Thon Buri",
    category: "crack",
    publicStatus: "fixed",
    detailedStatus: "resolved",
    publicLatitude: 13.7218,
    publicLongitude: 100.5012,
    localityLabel: "Krung Thon Buri Road, Khlong San",
    description: "Expansion joint rubber seal dislodged with 3cm metal lip exposed.",
    locationContext: "Taksin Bridge westbound approach",
    exactLocation: {
      latitude: 13.72182,
      longitude: 100.50118,
      accuracyMeters: 3.8,
      source: "gps",
      capturedAt: "2026-09-15T09:00:00Z",
      localityLabel: "Krung Thon Buri Road, Khlong San",
    },
    publicLocation: {
      latitude: 13.7218,
      longitude: 100.5012,
      localityLabel: "Krung Thon Buri Road, Khlong San",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-007",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "bridge_joint.jpg",
        byteSize: 1100000,
        isSanitized: true,
        createdAt: "2026-09-15T09:00:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "crack",
          score: 0.93,
          boundingBox: { x: 180, y: 200, width: 350, height: 120 },
        },
      ],
      primaryCategory: "crack",
      suggestedSeverity: "high",
      summary: "Bridge joint exposure requiring elastomeric sealant replacement.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.93,
      isDemo: true,
    },
    operationalPriority: "p1",
    events: [
      {
        id: "evt-060",
        reportId: "rep-007",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Citizen hazard reported.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-15T09:00:00Z",
      },
      {
        id: "evt-061",
        reportId: "rep-007",
        fromStatus: "reported",
        toStatus: "resolved",
        publicNote: "Joint seal replaced and welded plates smoothed.",
        actorName: "Bridge Engineering Division",
        actorRole: "staff",
        resolutionEvidenceUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
        createdAt: "2026-09-17T18:00:00Z",
      },
    ],
    resolvedAt: "2026-09-17T18:00:00Z",
    version: 2,
    createdAt: "2026-09-15T09:00:00Z",
    updatedAt: "2026-09-17T18:00:00Z",
  },
  {
    id: "rep-008",
    publicId: "RD-2026-0838",
    title: "Cluster of Potholes on Thong Lo Soi 10",
    category: "pothole",
    publicStatus: "reported",
    detailedStatus: "acknowledged",
    publicLatitude: 13.7335,
    publicLongitude: 100.5821,
    localityLabel: "Thong Lo 10, Watthana",
    description: "Three consecutive potholes in narrow residential lane causing swerving.",
    locationContext: "Near The Commons Thonglor",
    exactLocation: {
      latitude: 13.73351,
      longitude: 100.58214,
      accuracyMeters: 4.1,
      source: "gps",
      capturedAt: "2026-09-28T07:20:00Z",
      localityLabel: "Thong Lo 10, Watthana",
    },
    publicLocation: {
      latitude: 13.7335,
      longitude: 100.5821,
      localityLabel: "Thong Lo 10, Watthana",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-008",
        url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "thonglo_potholes.jpg",
        byteSize: 1180000,
        isSanitized: true,
        createdAt: "2026-09-28T07:20:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "pothole",
          score: 0.95,
          boundingBox: { x: 120, y: 180, width: 160, height: 110 },
        },
        {
          category: "pothole",
          score: 0.88,
          boundingBox: { x: 310, y: 220, width: 140, height: 95 },
        },
      ],
      primaryCategory: "pothole",
      suggestedSeverity: "high",
      summary: "Multiple adjacent impact holes detected.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.95,
      isDemo: true,
    },
    operationalPriority: "p2",
    events: [
      {
        id: "evt-070",
        reportId: "rep-008",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Resident reported 3 potholes in lane.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-28T07:20:00Z",
      },
      {
        id: "evt-071",
        reportId: "rep-008",
        fromStatus: "reported",
        toStatus: "acknowledged",
        publicNote: "Assigned to Watthana district inspection itinerary.",
        actorName: "Central Dispatch",
        actorRole: "staff",
        createdAt: "2026-09-28T08:15:00Z",
      },
    ],
    version: 2,
    createdAt: "2026-09-28T07:20:00Z",
    updatedAt: "2026-09-28T08:15:00Z",
  },
  {
    id: "rep-009",
    publicId: "RD-2026-0810",
    title: "Surface Deterioration on Din Daeng Triangle",
    category: "surface_wear",
    publicStatus: "fixed",
    detailedStatus: "resolved",
    publicLatitude: 13.7628,
    publicLongitude: 100.5482,
    localityLabel: "Din Daeng, Ratchathewi",
    description: "Bleeding bitumen and loss of skid resistance on roundabout curve.",
    locationContext: "Din Daeng junction",
    exactLocation: {
      latitude: 13.76281,
      longitude: 100.54819,
      accuracyMeters: 4.5,
      source: "gps",
      capturedAt: "2026-09-20T15:30:00Z",
      localityLabel: "Din Daeng, Ratchathewi",
    },
    publicLocation: {
      latitude: 13.7628,
      longitude: 100.5482,
      localityLabel: "Din Daeng, Ratchathewi",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-009",
        url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "dindaeng_wear.jpg",
        byteSize: 1200000,
        isSanitized: true,
        createdAt: "2026-09-20T15:30:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "surface_wear",
          score: 0.91,
          boundingBox: { x: 100, y: 150, width: 400, height: 280 },
        },
      ],
      primaryCategory: "surface_wear",
      suggestedSeverity: "medium",
      summary: "Loss of aggregate friction layer.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.91,
      isDemo: true,
    },
    operationalPriority: "p2",
    events: [
      {
        id: "evt-080",
        reportId: "rep-009",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Report submitted.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-20T15:30:00Z",
      },
      {
        id: "evt-081",
        reportId: "rep-009",
        fromStatus: "reported",
        toStatus: "resolved",
        publicNote: "High-friction surfacing applied and tested for skid resistance.",
        actorName: "Highways Department",
        actorRole: "staff",
        resolutionEvidenceUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80",
        createdAt: "2026-09-24T06:00:00Z",
      },
    ],
    resolvedAt: "2026-09-24T06:00:00Z",
    version: 2,
    createdAt: "2026-09-20T15:30:00Z",
    updatedAt: "2026-09-24T06:00:00Z",
  },
  {
    id: "rep-010",
    publicId: "RD-2026-0841",
    title: "Trench Collapse after Pipe Repair on Charoen Krung",
    category: "subsidence",
    publicStatus: "reported",
    detailedStatus: "assessing",
    publicLatitude: 13.7291,
    publicLongitude: 100.5142,
    localityLabel: "Charoen Krung Road, Bang Rak",
    description: "Utility trench backfill sank 8cm below road grade.",
    locationContext: "Outside Old Custom House alley",
    exactLocation: {
      latitude: 13.72908,
      longitude: 100.51419,
      accuracyMeters: 5.0,
      source: "gps",
      capturedAt: "2026-09-28T11:00:00Z",
      localityLabel: "Charoen Krung Road, Bang Rak",
    },
    publicLocation: {
      latitude: 13.7291,
      longitude: 100.5142,
      localityLabel: "Charoen Krung Road, Bang Rak",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-010",
        url: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "charoenkrung_trench.jpg",
        byteSize: 1020000,
        isSanitized: true,
        createdAt: "2026-09-28T11:00:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "subsidence",
          score: 0.92,
          boundingBox: { x: 140, y: 170, width: 360, height: 230 },
        },
      ],
      primaryCategory: "subsidence",
      suggestedSeverity: "high",
      summary: "Linear subsidence along utility excavation alignment.",
      needsHumanReview: true,
      imageQualityIssues: [],
      confidenceScore: 0.92,
      isDemo: true,
    },
    operationalPriority: "p2",
    events: [
      {
        id: "evt-090",
        reportId: "rep-010",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Citizen filed report on uneven utility patch.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-28T11:00:00Z",
      },
      {
        id: "evt-091",
        reportId: "rep-010",
        fromStatus: "reported",
        toStatus: "assessing",
        publicNote: "Utility contractor notified for warranty re-compaction.",
        actorName: "District Oversight",
        actorRole: "staff",
        createdAt: "2026-09-28T12:00:00Z",
      },
    ],
    version: 2,
    createdAt: "2026-09-28T11:00:00Z",
    updatedAt: "2026-09-28T12:00:00Z",
  },
  {
    id: "rep-011",
    publicId: "RD-2026-0815",
    title: "Cracked Curb & Gutter Spalling on Yaowarat Road",
    category: "crack",
    publicStatus: "repairing",
    detailedStatus: "repairing",
    publicLatitude: 13.7412,
    publicLongitude: 100.5085,
    localityLabel: "Yaowarat Road, Samphanthawong",
    description: "Curbside concrete crumbling into drainage line.",
    locationContext: "Near Chinatown Gate",
    exactLocation: {
      latitude: 13.74119,
      longitude: 100.50848,
      accuracyMeters: 4.2,
      source: "gps",
      capturedAt: "2026-09-24T17:00:00Z",
      localityLabel: "Yaowarat Road, Samphanthawong",
    },
    publicLocation: {
      latitude: 13.7412,
      longitude: 100.5085,
      localityLabel: "Yaowarat Road, Samphanthawong",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-011",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "yaowarat_curb.jpg",
        byteSize: 1150000,
        isSanitized: true,
        createdAt: "2026-09-24T17:00:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "crack",
          score: 0.87,
          boundingBox: { x: 210, y: 190, width: 280, height: 150 },
        },
      ],
      primaryCategory: "crack",
      suggestedSeverity: "low",
      summary: "Curb concrete spalling without immediate roadbed threat.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.87,
      isDemo: true,
    },
    operationalPriority: "p3",
    events: [
      {
        id: "evt-100",
        reportId: "rep-011",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Report submitted.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-24T17:00:00Z",
      },
      {
        id: "evt-101",
        reportId: "rep-011",
        fromStatus: "reported",
        toStatus: "repairing",
        publicNote: "Masonry crew recasting curb section.",
        actorName: "Samphanthawong Masonry Crew",
        actorRole: "staff",
        createdAt: "2026-09-28T08:00:00Z",
      },
    ],
    assignedTeam: {
      id: "team-04",
      name: "Heritage District Maintenance",
      publicDisplayName: "Chinatown Heritage District Crew",
    },
    version: 2,
    createdAt: "2026-09-24T17:00:00Z",
    updatedAt: "2026-09-28T08:00:00Z",
  },
  {
    id: "rep-012",
    publicId: "RD-2026-0805",
    title: "Large Pothole near Chatuchak Weekend Market",
    category: "pothole",
    publicStatus: "fixed",
    detailedStatus: "resolved",
    publicLatitude: 13.7998,
    publicLongitude: 100.5512,
    localityLabel: "Kamphaeng Phet 2 Road, Chatuchak",
    description: "Deep pothole at market entry lane.",
    locationContext: "Gate 1 Chatuchak Park",
    exactLocation: {
      latitude: 13.79979,
      longitude: 100.55122,
      accuracyMeters: 3.9,
      source: "gps",
      capturedAt: "2026-09-21T08:00:00Z",
      localityLabel: "Kamphaeng Phet 2 Road, Chatuchak",
    },
    publicLocation: {
      latitude: 13.7998,
      longitude: 100.5512,
      localityLabel: "Kamphaeng Phet 2 Road, Chatuchak",
      isGeneralized: true,
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80",
    media: [
      {
        id: "med-012",
        url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
        thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=400&q=80",
        mimeType: "image/jpeg",
        fileName: "chatuchak_pothole.jpg",
        byteSize: 1310000,
        isSanitized: true,
        createdAt: "2026-09-21T08:00:00Z",
      },
    ],
    aiAnalysis: {
      provider: "roboflow",
      model: "road-damage-detection-v4",
      labels: [
        {
          category: "pothole",
          score: 0.98,
          boundingBox: { x: 190, y: 160, width: 250, height: 180 },
        },
      ],
      primaryCategory: "pothole",
      suggestedSeverity: "high",
      summary: "Pothole depth over 10cm.",
      needsHumanReview: false,
      imageQualityIssues: [],
      confidenceScore: 0.98,
      isDemo: true,
    },
    operationalPriority: "p1",
    events: [
      {
        id: "evt-110",
        reportId: "rep-012",
        fromStatus: undefined,
        toStatus: "reported",
        publicNote: "Report logged.",
        actorName: "Resident Reporter",
        actorRole: "reporter",
        createdAt: "2026-09-21T08:00:00Z",
      },
      {
        id: "evt-111",
        reportId: "rep-012",
        fromStatus: "reported",
        toStatus: "resolved",
        publicNote: "Hot-mix asphalt patch installed and compacted.",
        actorName: "Chatuchak Works Team",
        actorRole: "staff",
        resolutionEvidenceUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80",
        createdAt: "2026-09-23T16:00:00Z",
      },
    ],
    resolvedAt: "2026-09-23T16:00:00Z",
    version: 2,
    createdAt: "2026-09-21T08:00:00Z",
    updatedAt: "2026-09-23T16:00:00Z",
  },
];
